---

- name: install docker-ce
  become: yes
  apt: pkg=docker-ce state=present update_cache=yes

- name: start docker
  become: yes
  service: name=docker state=started enabled=yes

- name: add docker group
  become: yes
  group: name=docker

- name: install python-pip
  apt: pkg=python-pip state=present

- name: install docker-py
  become: yes
  apt: pkg=docker-py state=present
