---

- name: install docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: "{{ docker_compose_path }}"
    mode: 0755
