---

- name: install docker_common
  include: docker_common.yml

- name: install docker
  include: docker.yml
  when: install_docker

- name: set {{ docker_user }} into docker group
  include: docker_user.yml
  when: docker_user is defined

- name: install docker-compose
  include: docker_compose.yml
  when: install_docker_compose
